### ISSUE TITLE
Fix the array issues

### ISSUE THREAD

**Issue by mattpiccolella** [mayankmahajan24/QL#30]
Can't pass arrays as functions, `length(array)`needs to be done, then also allocating an array of a given length

**Comment by evantarrh** [comment]
- [ ] pass arrays as functions
- [x] `length(array)`
- [x] Allocate array of given length

**Comment by anshulkgupta** [comment]
what does "pass arrays as functions" mean? is that referring to inside function calls?

**Comment by mayankmahajan24** [comment]
I think he meant pass arrays as arguments to functions

On Tuesday, December 15, 2015, Anshul Gupta notifications@github.com
wrote:

> what does "pass arrays as functions" means? is that referring to inside
> function calls?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mayankmahajan24/QL/issues/30#issuecomment-164805527.

## 

Mayank Mahajan

Columbia University | Class of 2017
B.S. Computer Science
mm4399@columbia.edu
www.linkedin.com/in/mmahajan24/
571.212.5535

**Comment by evantarrh** [comment]
ding ding ding! don't know what me and matt were thinking when we were scoping this out. i moved that particular issue into a different branch because it turns out that that's a lot harder

**Comment by evantarrh** [comment]
closing this because of #37 and opening a new issue for array args to functions
